apiVersion: solution.sap/v1
kind: Solution

metadata:
  name: hello-world-agent-a9322
  version: 1.0.0
  description: A minimal AI agent that replies with Hello World to any input message.

assets:
  - ref: ./assets/hello-world-agent/asset.yaml

# run: 2026-08-27 12:54:43
# run: 2026-08-27 13:09:41
# run: 2026-08-27 13:32:53
# run: 2026-08-27 14:47:28